### ISSUE TITLE
Wholesale discount.

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [loki79uk/BulkBuy#2]
Today I thought: why didn't the seller reduce the price when I bought 10 bags of feed from him? Well, at least 5% when buying 10 bags.
This is an idea for the future. Maybe you will be able to implement it someday.

**Comment by loki79uk** [comment]
Hi,  I did think of that in the beginning and even coded it, but because you often ended up with strange fractions of prices I was worried that people may not like it.  I could certainly make it an option in future releases.

Thanks for the input though, it is helpful to know what people want!
