### ISSUE TITLE
Options cost

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [loki79uk/BulkBuy#4]
This function seems broken. Money summarizes correctly, but does not show it.
![screenshot0](https://user-images.githubusercontent.com/8200153/135469671-778d5557-4eae-44d9-a2b3-f028781e51f4.jpg)

**Comment by Gonimy-Vetrom** [comment]
![fsScreen_2021_09_30_17_17_52_2](https://user-images.githubusercontent.com/8200153/135472845-1b8408d9-3fe1-4883-a22a-d95d7e665ba4.png)

**Comment by loki79uk** [comment]
Hi, is this with the new version from ModHub?  For me that is working on default pallets and items from the 'Lizard Pallet Pack'.

Is the pallet in your second screenshot from a mod?  I don't recoginise the first option selection.

![image](https://user-images.githubusercontent.com/76516343/135475168-99f01115-75b6-403d-921b-62a3cfecc488.png)
![image](https://user-images.githubusercontent.com/76516343/135475218-e38d7548-2cf7-4202-8090-0095133dbd2b.png)

**Comment by Gonimy-Vetrom** [comment]
Yes, this is the new version from ModHub. 
The second option for the standard tank appears if the "ManureSystem" mod is installed (install the attacher for the hose or not).
Now I will try without mods.

**Comment by Gonimy-Vetrom** [comment]
While checked with mods. For bales (even bale-mod from MaizePlus) works correctly.
But for other things - no.
![fsScreen_2021_09_30_17_53_45](https://user-images.githubusercontent.com/8200153/135479478-dacbdeb5-eb94-45d7-9a6f-616de0b31519.png)
![fsScreen_2021_09_30_17_54_34](https://user-images.githubusercontent.com/8200153/135479503-6a38f409-7cab-47e9-a12a-713a829bf5cd.png)

**Comment by loki79uk** [comment]
Is there any chance you are using the Realistic Seeder Mod?  That has a script that conflicts with BulkBuy.

For me the sapling pallets work:
![image](https://user-images.githubusercontent.com/76516343/135480886-9e4a1bcb-5dba-4677-91d1-40d4f167f9fa.png)

**Comment by Gonimy-Vetrom** [comment]
Yes. I use this mod. But it seems until the latest update there was no such problem. 
It is necessary to find an old version and check.

Which of them are black sheep?

ChangeModTitle.lua
StoreManagerExtension.lua
StorageExtension.lua
RegisterFillTypes.lua
RegisterSpecialization.lua
RealisticSeederUtil.lua
AddStoreCategory.lua
BuyMorePallets.lua -

**Comment by loki79uk** [comment]
BuyMorePallets.lua is essentially a clone of the previous BulkBuy version, and because it is later in the alphabet, I think it replaces Bulk buy completely.  So actually you are seeing the behaviour that I was trying to fix in the latest update.

HOWEVER - I now see there is a different conflict with BB 1.0.3.0 and Manure System!  The "install attacher for the hose or not" option does not appear at all when I use just those two mods together!

the MS conflict produces the following error:
```
2021-09-30 16:15 Error: Running LUA method 'mouseEvent'.
2021-09-30 16:15 dataS/scripts/gui/ShopConfigScreen.lua(333) : attempt to index local 'configs' (a nil value)
```

**Comment by Gonimy-Vetrom** [comment]
I deleted this script (commented on it in modDesc) and now everything works.
I did not meet such mistakes. I have not it.

**Comment by loki79uk** [comment]
That is good, but also strange you do not see this error.  Which version of Manure System do you have?  I was using the latest 1.2.0.0.  I will investigte some more, but glad we found the problem.

**Comment by loki79uk** [comment]
Also, I think (after commenting out that script) you will now find some pallets/bags from Realistic Seeder cannot be muliti-bought.  You should be able to add the types to BulkBuy, but I have not looked properly so can't give you the exact names required.

**Comment by Gonimy-Vetrom** [comment]
Yes, there is such a problem. When I start a new game.
But in my current game, this does not happen. Some script solves this problem probably: (

> You should be able to add the types to BulkBuy,

Good. I already did it before :)

**Comment by loki79uk** [comment]
Okay - thanks for confirming.  It always seems that after you fix one bug, there is another conflict!

I will look at the Manure System problem this evening.

I'll close this for now, but please open a new issue if you find anything else.
